// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DismissibleController from "./dismissible_controller"
application.register("dismissible", DismissibleController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import LinkController from "./link_controller"
application.register("link", LinkController)
