volumes:
  db_data:
    name: mcsc_db_data_dev

x-dev: &dev
  image: mcsc_app
  build: .
  env_file:
    - ./.env
  volumes:
    - .:/rails

x-dev-app: &dev-app
  <<: *dev
  environment:
    - DB_HOST=db
    - REDIS_HOST=redis
  depends_on:
    - db
    - redis

x-dev-assets: &dev-assets
  <<: *dev
  tty: true

services:
  db:
    image: postgres:14-alpine
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379

  smtp:
    image: dockage/mailcatcher
    ports:
      - 1025:1025
      - 8025:1080

  js:
    <<: *dev-assets
    command: yarn build --watch

  css:
    <<: *dev-assets
    command: yarn build:css --watch

  web:
    <<: *dev-app
    depends_on:
      - db
      - redis
      - js
      - css
    ports:
      - 3000:3000

  setup:
    <<: *dev-app
    command: bin/docker/setup
    profiles:
      - tools
