default: &default
  adapter: redis
  url: <%= MSC.settings.redis_url %>
  channel_prefix: <%= MSC.settings.redis_prefix %>

development:
  <<: *default

test:
  adapter: test

production:
<<: *default
