default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= MSC.settings.db_host %>
  username: <%= MSC.settings.db_user %>
  password: <%= MSC.settings.db_pass %>
  database: <%= MSC.settings.db_name %>
  pool: <%= MSC.settings.db_pool %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
